[project]
name = 'Smart-Contract-Therapeutic-Forest-Bathing-Program'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.forest-bathing-platform]
path = 'contracts/forest-bathing-platform.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
